name: Build and Deploy Docker Image to Personal Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get short commit SHA
        id: vars
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t mud-server:${{ env.COMMIT_SHA }} .

      - name: Save Docker Image to File
        run: docker save mud-server:${{ env.COMMIT_SHA }} -o mud-server.tar

      - name: Transfer Docker Image to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./mud-server.tar
          target: ~/_docker/mud_server

      - name: Run Docker Container
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/_docker/mud_server
            docker load -i ./mud-server.tar
            export IMAGE_TAG=${{ env.COMMIT_SHA }}
            docker compose down
            docker compose up -d
